language: generic

services:
  - docker

env:
  - DEPENDENCY_PACKAGES="git meson valac libgee-0.8 ninja-build"

install:
  - docker pull ubuntu:bionic

script:
  - ./run "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES"
  - ./run "git clone https://github.com/steveno/libbalistica.git"
  - ./run "cd libbalistica && mkdir build && meson . build/ && cd build && ninja"
  - ./run "test/libbalistica-test"
