language: generic

services:
  - docker

before-install:
  - docker build -t oliversteven/libbalistica .

script:
  - docker run -d oliversteveno/libbalistica /bin/sh -c "cd libbalistica/build/test && ./libbalistica-test"
